In [1]:
# task 1

import numpy as np
array_1d = np.arange(1, 11)
print("1D Array:\n", array_1d)
array_2d = np.arange(1, 10).reshape(3, 3)
print("\n2D Array:\n", array_2d)
array_3d = np.random.rand(3, 5, 3)
print("\n3D Array:\n", array_3d)
print("\n1D - Shape:", array_1d.shape, "Size:", array_1d.size, "Dtype:", array_1d.dtype)
print("2D - Shape:", array_2d.shape, "Size:", array_2d.size, "Dtype:", array_2d.dtype)
print("3D - Shape:", array_3d.shape, "Size:", array_3d.size, "Dtype:", array_3d.dtype)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
 [[[0.06759976 0.1017204  0.46742134]
  [0.75925852 0.86141366 0.77173791]
  [0.88763414 0.3904526  0.6522061 ]
  [0.88484217 0.3734677  0.84196078]
  [0.70380186 0.98961763 0.36528447]]

 [[0.40287726 0.26486721 0.59108711]
  [0.80869486 0.14036235 0.76003382]
  [0.86400762 0.06369278 0.21337172]
  [0.49082387 0.99932271 0.52421226]
  [0.3047907  0.95139008 0.03644613]]

 [[0.35359072 0.72368925 0.39910284]
  [0.52872144 0.80083448 0.06581753]
  [0.45290242 0.23554115 0.73343026]
  [0.78017155 0.22858084 0.56981134]
  [0.28698158 0.87671494 0.10799764]]]

1D - Shape: (10,) Size: 10 Dtype: int64
2D - Shape: (3, 3) Size: 9 Dtype: int64
3D - Shape: (3, 5, 3) Size: 45 Dtype: float64


In [2]:
# task 2

import numpy as np
array_1d = np.arange(1, 11)
print("1D Array:\n", array_1d)
array_2d = np.arange(1, 10).reshape(3, 3)
print("\n2D Array:\n", array_2d)
array_3d = np.random.rand(3, 5, 3)
print("\n3D Array:\n", array_3d)
print("\n1D - Shape:", array_1d.shape, "Size:", array_1d.size, "Dtype:", array_1d.dtype)
print("2D - Shape:", array_2d.shape, "Size:", array_2d.size, "Dtype:", array_2d.dtype)
print("3D - Shape:", array_3d.shape, "Size:", array_3d.size, "Dtype:", array_3d.dtype)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
 [[[0.26687669 0.65043288 0.46646929]
  [0.94250007 0.21119282 0.19210867]
  [0.61830278 0.21822773 0.8632184 ]
  [0.56582182 0.90153654 0.76129531]
  [0.33367498 0.5149415  0.75904698]]

 [[0.05639513 0.62686813 0.93472565]
  [0.8468493  0.50906213 0.38465481]
  [0.56432151 0.14124996 0.18317977]
  [0.20407468 0.89643    0.69797593]
  [0.33035865 0.54052192 0.78842222]]

 [[0.38558043 0.05006705 0.5843689 ]
  [0.03745299 0.00640611 0.48969326]
  [0.85912453 0.00214048 0.07458573]
  [0.36335103 0.77435897 0.45170119]
  [0.4515714  0.78112266 0.74632754]]]

1D - Shape: (10,) Size: 10 Dtype: int64
2D - Shape: (3, 3) Size: 9 Dtype: int64
3D - Shape: (3, 5, 3) Size: 45 Dtype: float64


In [3]:
# task 3

import numpy as np
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("Array A:", A)
print("Array B:", B)

print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)

print("Dot Product:", np.dot(A, B))

print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Std Dev of A:", np.std(A))
print("Variance of A:", np.var(A))

print("Max in B:", np.max(B), "at index", np.argmax(B))
print("Min in B:", np.min(B), "at index", np.argmin(B))

Array A: [14  2 19 15 17]
Array B: [16  2 18  6  4]
Addition: [30  4 37 21 21]
Subtraction: [-2  0  1  9 13]
Multiplication: [224   4 342  90  68]
Division: [0.875      1.         1.05555556 2.5        4.25      ]
Dot Product: 728
Mean of A: 13.4
Median of A: 15.0
Std Dev of A: 5.953150426454887
Variance of A: 35.440000000000005
Max in B: 18 at index 2
Min in B: 2 at index 1


In [4]:
# task 4

import numpy as np
arr = np.arange(1, 13)

reshaped_2d = arr.reshape(4, 3)
print("Reshaped to 2D (4x3):\n", reshaped_2d)

reshaped_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 3D (2x2x3):\n", reshaped_3d)

transposed = reshaped_2d.T
print("\nTransposed 2D array:\n", transposed)
print("Transposed shape:", transposed.shape)

Reshaped to 2D (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 3D (2x2x3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 2D array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transposed shape: (3, 4)


In [5]:
# task 5

import numpy as np
arr = np.random.randint(10, 51, 15)
print("Original Array:", arr)

print("Elements > 25:", arr[arr > 25])

arr[arr < 30] = 0
print("Replaced <30 with 0:", arr)

count_div5 = np.sum(arr % 5 == 0)
print("Count divisible by 5:", count_div5)

Original Array: [30 21 25 36 49 17 42 20 36 47 46 11 30 32 12]
Elements > 25: [30 36 49 42 36 47 46 30 32]
Replaced <30 with 0: [30  0  0 36 49  0 42  0 36 47 46  0 30 32  0]
Count divisible by 5: 8


In [6]:
# task 6

import numpy as np

linspace_arr = np.linspace(0, 1, 10)
print("Equally spaced (0 to 1):", linspace_arr)

identity = np.eye(4)
print("Identity Matrix (4x4):\n", identity)

rand_arr = np.random.randint(1, 101, 20)
sorted_arr = np.sort(rand_arr)
print("Sorted Array:", sorted_arr)
print("Top 5 elements:", sorted_arr[-5:])

Equally spaced (0 to 1): [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity Matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sorted Array: [ 7 12 21 24 26 39 43 47 49 52 53 55 64 64 71 71 73 81 85 89]
Top 5 elements: [71 73 81 85 89]


In [7]:
# task 7

import time
import numpy as np
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start_time = time.time()

product = np.dot(A, B)
try:
    det = np.linalg.det(product)
    inv = np.linalg.inv(product)
    print("Determinant:", det)
except np.linalg.LinAlgError:
    print("Matrix not invertible")

end_time = time.time()

print("Time taken:", end_time - start_time, "seconds")

Determinant: -1.4648501153161726e+50
Time taken: 0.0679783821105957 seconds
